// AUTO-GENERATED by scripts/update_light_pollution.py. Do not edit.
// Light-pollution dataset metadata for the runtime tile loader.
export interface LightPollutionMeta {
  datasetName: string;
  conceptDoi: string;
  datasetYear: number;
  sourceVersion: string;
  sourceRecord: number;
  generatedAt: string;
  license: string;
  processingVersion: string;
  topLat: number;
  leftLon: number;
  stepDeg: number;
  gridWidth: number;
  gridHeight: number;
  tileDeg: number;
  tilePixels: number;
  pMax: number;
  magAtQ0: number;
  magAtQ255: number;
}

export const LIGHT_POLLUTION_META: LightPollutionMeta = {
  "datasetName": "OpenGeoHub / Zenodo global VIIRS nighttime lights",
  "conceptDoi": "10.5281/zenodo.7750174",
  "datasetYear": 2024,
  "sourceVersion": "v0.4",
  "sourceRecord": 17294744,
  "generatedAt": "2026-10-07T20:14:15.889432+00:00",
  "license": "cc-by-4.0",
  "processingVersion": "2",
  "topLat": 87.37,
  "leftLon": -180.0,
  "stepDeg": 0.01666667,
  "gridWidth": 21600,
  "gridHeight": 8962,
  "tileDeg": 2.0,
  "tilePixels": 120,
  "pMax": 60.0,
  "magAtQ0": 7.7,
  "magAtQ255": 3.4
} as const;
