[[news]]
date = "2026-05"
content = "The [call for papers](https://vischi.org/ubicomp-workshop-home) for our UbiComp/ISWC 2026 workshop is now online."

[[news]]
date = "2026-04"
content = "Our abstract was accepted for an oral presentation at the HERA 2026 Doctoral Students Forum."

[[news]]
date = "2026-01"
content = "I have accepted my Ph.D. offer from Fudan University (starting in September 2026)."

[[news]]
date = "2025-09"
content = "Started as a Research Assistant at FDU-VIS Lab and began leading projects."

[[news]]
date = "2025-06"
content = "I earned my Master's Degree from Fudan University."
